const ICON_SPRITE_URL = 'icons/siyuan-icons.js';

let iconSpriteLoaded = false;

function loadIconSprite() {
  if (iconSpriteLoaded) return;
  const script = document.createElement('script');
  script.src = ICON_SPRITE_URL;
  document.head.appendChild(script);
  iconSpriteLoaded = true;
}

function siyuanIcon(name, options = {}) {
  const { width = 20, height = 20, color = 'currentColor', className = '' } = options;
  return `<svg width="${width}" height="${height}" class="${className}" style="flex-shrink:0;display:inline-block;vertical-align:middle;fill:${color};"><use href="#${name}"></use></svg>`;
}

function siyuanIconBtn(name, options = {}) {
  const { width = 20, height = 20, color = 'currentColor', className = '', title = '' } = options;
  return `<button type="button" class="icon-btn-svg ${className}" title="${title}" style="background:none;border:none;cursor:pointer;padding:4px;display:inline-flex;align-items:center;justify-content:center;border-radius:6px;color:${color};">${siyuanIcon(name, { width, height, color, className: '' })}</button>`;
}

const ICON_MAP = {
  folder: 'iconFolder',
  file: 'iconFile',
  files: 'iconFiles',
  bookmark: 'iconBookmark',
  build: 'iconBookmark',
  recent: 'iconInbox',
  inbox: 'iconInbox',
  scan: 'iconRefresh',
  refresh: 'iconRefresh',
  reload: 'iconHistory',
  history: 'iconHistory',
  fonts: 'iconFont',
  font: 'iconFont',
  fix: 'iconSettings',
  settings: 'iconSettings',
  homepage: 'iconGlobalGraph',
  graph: 'iconGraph',
  globalGraph: 'iconGlobalGraph',
  eye: 'iconEye',
  pin: 'iconPin',
  unpin: 'iconUnpin',
  theme: 'iconTheme',
  mode: 'iconMode',
  light: 'iconLight',
  dark: 'iconDark',
  help: 'iconHelp',
  trash: 'iconTrashcan',
  trashcan: 'iconTrashcan',
  clear: 'iconClear',
  replace: 'iconReplace',
  image: 'iconImage',
  video: 'iconVideo',
  save: 'iconCloudSucc',
  cloudSucc: 'iconCloudSucc',
  upload: 'iconUpload',
  download: 'iconDownload',
  export: 'iconDownload',
  gallery: 'iconGallery',
  close: 'iconClose',
  closeRound: 'iconCloseRound',
  check: 'iconCheck',
  info: 'iconInfo',
  warning: 'iconInfo',
  add: 'iconAdd',
  minus: 'iconUncheck',
  menu: 'iconMenu',
  list: 'iconList',
  edit: 'iconEdit',
  calendar: 'iconCalendar',
  lock: 'iconLock',
  unlock: 'iconUnlock',
  star: 'iconStar',
  tag: 'iconTags',
  tags: 'iconTags',
  drag: 'iconDrag',
  move: 'iconMove',
  back: 'iconBack',
  forward: 'iconForward',
  zoomIn: 'iconZoomIn',
  zoomOut: 'iconZoomOut',
  fullscreen: 'iconFullscreen',
  fullscreenExit: 'iconFullscreenExit',
  checkbox: 'iconCheck',
  unchecked: 'iconUncheck',
  indeterminate: 'iconIndeterminateCheck',
  indeterminateCheck: 'iconIndeterminateCheck',
  copy: 'iconCopy',
  paste: 'iconPaste',
  cut: 'iconCut',
  board: 'iconBoard',
  plugin: 'iconPlugin',
  database: 'iconDatabase',
  email: 'iconEmail',
  phone: 'iconPhone',
  users: 'iconUsers',
  groups: 'iconGroups',
  account: 'iconAccount',
  keyboard: 'iconKeymap',
  keymap: 'iconKeymap',
  clock: 'iconClock',
  key: 'iconKey',
  search: 'iconSearch',
  filter: 'iconFilter',
  sort: 'iconSort',
  format: 'iconFormat',
  sparkles: 'iconSparkles',
  sparkle: 'iconSparkles',
  terminal: 'iconTerminal',
  link: 'iconLink',
  linkOff: 'iconLinkOff',
  code: 'iconCode',
  bold: 'iconBold',
  italic: 'iconItalic',
  underline: 'iconUnderline',
  strike: 'iconStrike',
  quote: 'iconQuote',
  listItem: 'iconListItem',
  orderedList: 'iconOrderedList',
  h1: 'iconH1',
  h2: 'iconH2',
  h3: 'iconH3',
  h4: 'iconH4',
  h5: 'iconH5',
  h6: 'iconH6',
  paragraph: 'iconParagraph',
  line: 'iconLine',
  heading: 'iconHeadings',
  headings: 'iconHeadings',
  indent: 'iconIndent',
  outdent: 'iconOutdent',
  expand: 'iconExpand',
  contract: 'iconContract',
  splitTB: 'iconSplitTB',
  splitLR: 'iconSplitLR',
  layout: 'iconLayout',
  layoutRight: 'iconLayoutRight',
  layoutBottom: 'iconLayoutBottom',
  arrowDown: 'iconArrowDown',
  down: 'iconDown',
  up: 'iconUp',
  left: 'iconLeft',
  right: 'iconRight',
  play: 'iconPlay',
  pause: 'iconPause',
  record: 'iconRecord',
  home: 'iconLeftTop',
  view: 'iconPreview',
  preview: 'iconPreview',
  maximize: 'iconMax',
  minimize: 'iconMin',
  restore: 'iconRestore',
  feedback: 'iconFeedback',
  select: 'iconSelect',
  selectText: 'iconSelectText',
  super: 'iconSuper',
  ref: 'iconRef',
  mark: 'iconMark',
  focus: 'iconFocus',
  exact: 'iconExact',
  regex: 'iconRegex',
  sql: 'iconSQL',
  math: 'iconMath',
  table: 'iconTable',
  deleteRow: 'iconDeleteRow',
  deleteColumn: 'iconDeleteColumn',
  alignLeft: 'iconAlignLeft',
  alignCenter: 'iconAlignCenter',
  alignRight: 'iconAlignRight',
  scrollWrap: 'iconScrollWrapped',
  scrollVert: 'iconScrollVert',
  scrollHoriz: 'iconScrollHoriz',
  softWrap: 'iconSoftWrap',
  spreadOdd: 'iconSpreadOdd',
  spreadEven: 'iconSpreadEven',
  spread: 'iconSpreadOdd',
  leftBottom: 'iconLeftBottom',
  bottomLeft: 'iconBottomLeft',
  rightBottom: 'iconRightBottom',
  bottomRight: 'iconBottomRight',
  rightTop: 'iconRightTop',
  topRight: 'iconTopRight',
  leftTop: 'iconLeftTop',
  topLeft: 'iconTopLeft',
  workspace: 'iconWorkspace',
  dock: 'iconDock',
  hideDock: 'iconHideDock',
  quit: 'iconQuit',
  cloudError: 'iconCloudError',
  cloudOff: 'iconCloudOff',
  cloud: 'iconCloud',
  attr: 'iconAttr',
  imgDown: 'iconImgDown',
  camera: 'iconCamera',
  vip: 'iconVIP',
  language: 'iconLanguage',
  rtl: 'iconRtl',
  ltr: 'iconLtr',
  keyboardHide: 'iconKeyboardHide',
  biu: 'iconBIU',
  html5: 'iconHTML5',
  github: 'iconGithub',
  githubI: 'iconGitHubI',
  markdown: 'iconMarkdown',
  mp: 'iconMp',
  pdf: 'iconPDF',
  card: 'iconFiles',
  cards: 'iconFilesRoot',
  dot: 'iconDot',
  transform: 'iconTransform',
  hand: 'iconHand',
};

function getIcon(name, options = {}) {
  const iconName = ICON_MAP[name] || name;
  return siyuanIcon(iconName, options);
}

function getIconBtn(name, options = {}) {
  const iconName = ICON_MAP[name] || name;
  return siyuanIconBtn(iconName, options);
}
